webtalk_init -webtalk_dir /media/narendiran/MOVIES/DeMosaicBased/VivadoProjects/project_1/project_1.sim/sim_1/behav/xsim/xsim.dir/tbBayerReconstructionTestOut_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sun Jun  6 06:01:12 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2552052" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "9e9df523-d372-439d-a6b7-3b81efff279b" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "fd0a79f8ed48405e98e47d5f2e17aa5b" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "54" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 20.04.2 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2600.000 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "12.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "101090 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "1.11_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "119560_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2825128075 -regid "" -xml /media/narendiran/MOVIES/DeMosaicBased/VivadoProjects/project_1/project_1.sim/sim_1/behav/xsim/xsim.dir/tbBayerReconstructionTestOut_behav/webtalk/usage_statistics_ext_xsim.xml -html /media/narendiran/MOVIES/DeMosaicBased/VivadoProjects/project_1/project_1.sim/sim_1/behav/xsim/xsim.dir/tbBayerReconstructionTestOut_behav/webtalk/usage_statistics_ext_xsim.html -wdm /media/narendiran/MOVIES/DeMosaicBased/VivadoProjects/project_1/project_1.sim/sim_1/behav/xsim/xsim.dir/tbBayerReconstructionTestOut_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
